name: ci

on:
    push:
        branches:
            - master

jobs:
    test_phaser:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Update local toolchain
              run: |
                  rustup update
                  rustup install nightly

            - name: Toolchain info
              run: |
                  cargo --version --verbose
                  rustc --version

            - name: Test
              run: |

                  cargo check
                  cargo test --all

            - name: Build
              run: |
                  cargo build --release
